server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuanyifeng/yyf-sc-learning.git      # 配置Git仓库的地址
          search-paths: microservice-config-server
          username: yuanyifeng                                                         # Git仓库的账号
          password: fengnuoyang1110                                                     # Git仓库的密码
name: dev-yyf
profile: dev-1.0