name: yyf
profile: default-1.0
server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/itmuch/spring-cloud-config-repo     # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                  # Git仓库的密码
